services:
  app:
    build:
      dockerfile: Dockerfile

  app2:
    build:
      dockerfile: Dockerfile.app2

  app_dc:
    build:
      dockerfile: Dockerfile.dc

  app_web:
    build:
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"
